# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_permutations_cpp <- function(vid_pairs_idx, met_ids_encoded, a_pairs, base_weights, V, n_perm, seed) {
    .Call(`_featuremsea_compute_permutations_cpp`, vid_pairs_idx, met_ids_encoded, a_pairs, base_weights, V, n_perm, seed)
}

